$(document).ready(function() {
$("input#autocomplete").autocomplete({
source: [
{ value: "The Alps", url: 'https://superalpine.co/alps/index.html' },
{ value: "Bond in the Alps", url: 'https://superalpine.co/alps/bond-in-the-alps/index.html' },
{ value: "A view to a kill", url: 'https://superalpine.co/alps/bond-in-the-alps/a-view-to-a-kill.html'},
{ value: "Casino Royale", url: 'https://superalpine.co/alps/bond-in-the-alps/casino-royale.html'},
{ value: "For your eyes only", url: 'https://superalpine.co/alps/bond-in-the-alps/for-your-eyes-only.html'},
{ value: "From Russia with love", url: 'https://superalpine.co/alps/bond-in-the-alps/from-russia-with-love.html'},
{ value: "Goldfinger", url: 'https://superalpine.co/alps/bond-in-the-alps/goldfinger.html'},
{ value: "Goldeneye", url: 'https://superalpine.co/alps/bond-in-the-alps/goldeneye.html'},
{ value: "Octopussy", url: 'https://superalpine.co/alps/bond-in-the-alps/octopussy.html'},
{ value: "On Her Majesty's Secret Service", url: 'https://superalpine.co/alps/bond-in-the-alps/on-her-majestys-secret-service.html'},
{ value: "Quantum of solace", url: 'https://superalpine.co/alps/bond-in-the-alps/quantum-of-solace.html'},
{ value: "SPECTRE", url: 'https://superalpine.co/alps/bond-in-the-alps/spectre.html'},
{ value: "The spy who loved me", url: 'https://superalpine.co/alps/bond-in-the-alps/the-spy-who-loved-me.html'},
{ value: "The world is not enough", url: 'https://superalpine.co/alps/bond-in-the-alps/the-world-is-not-enough.html'},
{ value: "You only live twice", url: 'https://superalpine.co/alps/bond-in-the-alps/you-only-live-twice.html'},
{ value: "Scrambles Amongst the Alps", url: 'https://superalpine.co/scrambles-amongst-the-alps/index.html' },
{ value: "Innsbruck", url: 'https://superalpine.co/austria/innsbruck/index.html' },
{ value: "Ischgl", url: 'https://superalpine.co/austria/ischgl/index.html' },
{ value: "Chamonix Travel Guide", url: 'https://superalpine.co/chamonix-travel-guide/index.html' },
{ value: "Cirque du fer à Cheval", url: 'https://superalpine.co/france/cirque-du-fer-a-cheval/index.html' },
{ value: "Col de Joux Plane", url: 'https://superalpine.co/france/col-de-joux-plane/index.html' },
{ value: "Col de l'Iseran", url: 'https://superalpine.co/france/col-de-l-iseran/index.html' },
{ value: "Col de Turini", url: 'https://superalpine.co/france/col-de-turini/index.html' },
{ value: "Col du Petit Saint-Bernard", url: 'https://superalpine.co/france/col-du-petit-saint-bernard/index.html' },
{ value: "Cristal de Jade, Chamonix", url: 'https://superalpine.co/hotel-reviews/cristal-de-jade-chamonix-review.html' },
{ value: "Fort de la Redoute Ruinée", url: 'https://superalpine.co/france/fort-de-la-redoute-ruinee/index.html' },
{ value: "La Grave", url: 'https://superalpine.co/france/la-grave/index.html' },
{ value: "Nietzsche Trail", url: 'https://superalpine.co/france/nietzsche-trail/index.html' },
{ value: "Route des Grandes Alpes", url: 'https://superalpine.co/france/route-des-grandes-alpes/index.html' },
{ value: "Route Napoléon", url: 'https://superalpine.co/france/route-napoleon/index.html' },
{ value: "Saint-Jean-Cap-Ferrat", url: 'https://superalpine.co/france/saint-jean-cap-ferrat/index.html' },
{ value: "The Alpine Line", url: 'https://superalpine.co/france/alpine-line/index.html' },
{ value: "Vanoise National Park", url: 'https://superalpine.co/france/vanoise-national-park/index.html' },
{ value: "Aosta", url: 'https://superalpine.co/italy/aosta/index.html' },
{ value: "Messner Mountain Museum Corones", url:'https://superalpine.co/italy/messner-mountain-museum-corones/index.html'};
{ value: "Monaco", url: 'https://superalpine.co/monaco/index.html' },
{ value: "Oceanographic Museum of Monaco", url: 'https://superalpine.co/monaco/oceanographic-museum-monaco/index.html' },
{ value: "Andermatt", url: 'https://superalpine.co/switzerland/andermatt/index.html' },
{ value: "Crans Montana", url: 'https://superalpine.co/switzerland/crans-montana/index.html' },
{ value: "Radisson Blu Reussen hotel, Andermatt", url: 'https://superalpine.co/hotel-reviews/radisson-blu-andermatt-review.html' },
{ value: "Revier Mountain Lodge hotel, Lenzerheide", url: 'https://superalpine.co/hotel-reviews/revier-mountain-lodge-lenzerheide-review.html' },
{ value: "Saas Fee Glacier Bike 1999", url: 'https://superalpine.co/switzerland/saas-fee-glacier-bike-1999/index.html' },
{ value: "Swiss Passes", url: 'https://superalpine.co/swiss-passes/index.html' },
{ value: "Albula pass",  url: 'https://superalpine.co/swiss-passes/albula-pass.html' },
{ value: "Bernina pass",  url: 'https://superalpine.co/swiss-passes/bernina-pass.html' },
{ value: "Col de Champex",  url: 'https://superalpine.co/swiss-passes/col-de-champex.html' },
{ value: "Col de la Croix",  url: 'https://superalpine.co/swiss-passes/col-de-la-croix.html' },
{ value: "Col de la Forclaz",  url: 'https://superalpine.co/swiss-passes/col-de-la-forclaz.html' },
{ value: "Col du Marchairuz",  url: 'https://superalpine.co/swiss-passes/col-du-marchairuz.html' },
{ value: "Col des Mosses",  url: 'https://superalpine.co/swiss-passes/col-des-mosses.html' },
{ value: "Col du Pillon",  url: 'https://superalpine.co/swiss-passes/col-du-pillon.html' },
{ value: "Flüela pass",  url: 'https://superalpine.co/swiss-passes/fluela-pass.html' },
{ value: "Furka pass",  url: 'https://superalpine.co/swiss-passes/furka-pass.html' },
{ value: "Great Saint-Bernard pass",  url: 'https://superalpine.co/swiss-passes/great-saint-bernard-pass.html' },
{ value: "Gotthard pass",  url: 'https://superalpine.co/swiss-passes/gotthard-pass.html' },
{ value: "Grimsel pass",  url: 'https://superalpine.co/swiss-passes/grimsel-pass.html' },
{ value: "Jaun pass",  url: 'https://superalpine.co/swiss-passes/jaun-pass.html' },
{ value: "Julier pass",  url: 'https://superalpine.co/swiss-passes/julier-pass.html' },
{ value: "Klausen pass",  url: 'https://superalpine.co/swiss-passes/klausen-pass.html' },
{ value: "Lukmanier pass",  url: 'https://superalpine.co/swiss-passes/lukmanier-pass.html' },
{ value: "Majola pass",  url: 'https://superalpine.co/swiss-passes/maloja-pass.html' },
{ value: "Nufenen pass",  url: 'https://superalpine.co/swiss-passes/nufenen-pass.html' },
{ value: "Oberalp pass",  url: 'https://superalpine.co/swiss-passes/oberalp-pass.html' },
{ value: "Ofen / Fuorn pass",  url: 'https://superalpine.co/swiss-passes/ofen-pass.html' },
{ value: "San Bernardino pass",  url: 'https://superalpine.co/swiss-passes/san-bernardino-pass.html' },
{ value: "Simplon pass",  url: 'https://superalpine.co/swiss-passes/simplon-pass.html' },
{ value: "Splügen pass",  url: 'https://superalpine.co/swiss-passes/splugen-pass.html' },
{ value: "Susten pass",  url: 'https://superalpine.co/swiss-passes/susten-pass.html' },
{ value: "Umbrail pass",  url: 'https://superalpine.co/swiss-passes/umbrail-pass.html' },
{ value: "Zermatt", url: 'https://superalpine.co/switzerland/zermatt/index.html' },
{ value: "Store", url: 'https://superalpine.co/https://store.superalpine.co' },
{ value: "Books", url: 'https://superalpine.co/https://store.superalpine.co' },
{ value: "Magazine", url: 'https://superalpine.co/magazine/index.html' },
{ value: "Newsletter", url: 'https://superalpine.co/newsletter/index.html' },
{ value: "Contact Super Alpine", url: 'https://superalpine.co/about/index.html' },
{ value: "Hotel reviews", url: 'https://superalpine.co/hotel-reviews/index.html' },
{ value: "Terms and conditions", url: 'https://superalpine.co/terms/index.html' }
],
select: function (event, ui) {
window.location = ui.item.url;
}
});
});