 $(document).ready(function() {
    $("input#autocomplete").autocomplete({
        source: [
            { value: "The Alps", url: 'alps/index.html' },
            { value: "Bond in the Alps", url: 'alps/bond-in-the-alps/index.html' },
            { value: "A view to a kill", url: 'alps/bond-in-the-alps/a-view-to-a-kill.html'},
            { value: "Casino Royale", url: 'alps/bond-in-the-alps/casino-royale.html'},
            { value: "For your eyes only", url: 'alps/bond-in-the-alps/for-your-eyes-only.html'},
            { value: "From Russia with love", url: 'alps/bond-in-the-alps/from-russia-with-love.html'},
            { value: "Goldfinger", url: 'alps/bond-in-the-alps/goldfinger.html'},
            { value: "Goldeneye", url: 'alps/bond-in-the-alps/goldeneye.html'},
            { value: "Octopussy", url: 'alps/bond-in-the-alps/octopussy.html'},
            { value: "On Her Majesty's Secret Service", url: 'alps/bond-in-the-alps/on-her-majestys-secret-service.html'},
            { value: "Quantum of solace", url: 'alps/bond-in-the-alps/quantum-of-solace.html'},
            { value: "SPECTRE", url: 'alps/bond-in-the-alps/spectre.html'},
            { value: "The spy who loved me", url: 'alps/bond-in-the-alps/the-spy-who-loved-me.html'},
            { value: "The world is not enough", url: 'alps/bond-in-the-alps/the-world-is-not-enough.html'},
            { value: "You only live twice", url: 'alps/bond-in-the-alps/you-only-live-twice.html'},
            { value: "Scrambles Amongst the Alps", url: 'scrambles-amongst-the-alps/index.html' },
            { value: "Innsbruck", url: 'austria/innsbruck/index.html' },
            { value: "Ischgl", url: 'austria/ischgl/index.html' },
            { value: "Chamonix Travel Guide", url: 'chamonix-travel-guide/index.html' },
            { value: "Cirque du fer à Cheval", url: 'france/cirque-du-fer-a-cheval/index.html' },
            { value: "Col de Joux Plane", url: 'france/col-de-joux-plane/index.html' },
            { value: "Col de l'Iseran", url: 'france/col-de-l-iseran/index.html' },
            { value: "Col de Turini", url: 'france/col-de-turini/index.html' },
            { value: "Col du Petit Saint-Bernard", url: 'france/col-du-petit-saint-bernard/index.html' },
            { value: "Cristal de Jade, Chamonix", url: 'hotel-reviews/cristal-de-jade-chamonix-review.html' },
            { value: "Fort de la Redoute Ruinée", url: 'france/fort-de-la-redoute-ruinee/index.html' },
            { value: "La Grave", url: 'france/la-grave/index.html' },
            { value: "Nietzsche Trail", url: 'france/nietzsche-trail/index.html' },
            { value: "Route des Grandes Alpes", url: 'france/route-des-grandes-alpes/index.html' },
            { value: "Route Napoléon", url: 'france/route-napoleon/index.html' },
            { value: "Saint-Jean-Cap-Ferrat", url: 'france/saint-jean-cap-ferrat/index.html' },
            { value: "The Alpine Line", url: 'france/alpine-line/index.html' },
            { value: "Vanoise National Park", url: 'france/vanoise-national-park/index.html' },
            { value: "Aosta", url: 'italy/aosta/index.html' },
            { value: "Monaco", url: 'monaco/index.html' },
            { value: "Oceanographic Museum of Monaco", url: 'monaco/oceanographic-museum-monaco/index.html' },
            { value: "Andermatt", url: 'switzerland/andermatt/index.html' },
            { value: "Crans Montana", url: 'switzerland/crans-montana/index.html' },
            { value: "Radisson Blu Reussen hotel, Andermatt", url: 'hotel-reviews/radisson-blu-andermatt-review.html' },
            { value: "Revier Mountain Lodge hotel, Lenzerheide", url: 'hotel-reviews/revier-mountain-lodge-lenzerheide-review.html' },
            { value: "Saas Fee Glacier Bike 1999", url: 'switzerland/saas-fee-glacier-bike-1999/index.html' },
            { value: "Swiss Passes", url: 'swiss-passes/index.html' },
            { value: "Albula pass",  url: 'swiss-passes/albula-pass.html' },
            { value: "Bernina pass",  url: 'swiss-passes/bernina-pass.html' },
            { value: "Col de Champex",  url: 'swiss-passes/col-de-champex.html' },
            { value: "Col de la Croix",  url: 'swiss-passes/col-de-la-croix.html' },
            { value: "Col de la Forclaz",  url: 'swiss-passes/col-de-la-forclaz.html' },
            { value: "Col du Marchairuz",  url: 'swiss-passes/col-du-marchairuz.html' },
            { value: "Col des Mosses",  url: 'swiss-passes/col-des-mosses.html' },
            { value: "Col du Pillon",  url: 'swiss-passes/col-du-pillon.html' },
            { value: "Flüela pass",  url: 'swiss-passes/fluela-pass.html' },
            { value: "Furka pass",  url: 'swiss-passes/furka-pass.html' },
            { value: "Great Saint-Bernard pass",  url: 'swiss-passes/great-saint-bernard-pass.html' },
            { value: "Gotthard pass",  url: 'swiss-passes/gotthard-pass.html' },
            { value: "Grimsel pass",  url: 'swiss-passes/grimsel-pass.html' },
            { value: "Jaun pass",  url: 'swiss-passes/jaun-pass.html' },
            { value: "Julier pass",  url: 'swiss-passes/julier-pass.html' },
            { value: "Klausen pass",  url: 'swiss-passes/klausen-pass.html' },
            { value: "Lukmanier pass",  url: 'swiss-passes/lukmanier-pass.html' },
            { value: "Majola pass",  url: 'swiss-passes/maloja-pass.html' },
            { value: "Nufenen pass",  url: 'swiss-passes/nufenen-pass.html' },
            { value: "Oberalp pass",  url: 'swiss-passes/oberalp-pass.html' },
            { value: "Ofen / Fuorn pass",  url: 'swiss-passes/ofen-pass.html' },
            { value: "San Bernardino pass",  url: 'swiss-passes/san-bernardino-pass.html' },
            { value: "Simplon pass",  url: 'swiss-passes/simplon-pass.html' },
            { value: "Splügen pass",  url: 'swiss-passes/splugen-pass.html' },
            { value: "Susten pass",  url: 'swiss-passes/susten-pass.html' },
            { value: "Umbrail pass",  url: 'swiss-passes/umbrail-pass.html' },
            { value: "Zermatt", url: 'switzerland/zermatt/index.html' },
            { value: "Store", url: 'https://store.superalpine.co' },
            { value: "Books", url: 'https://store.superalpine.co' },
            { value: "Magazine", url: 'magazine/index.html' },
            { value: "Newsletter", url: 'newsletter/index.html' },
            { value: "Contact Super Alpine", url: 'about/index.html' },
            { value: "Hotel reviews", url: 'hotel-reviews/index.html' },
            { value: "Terms and conditions", url: 'terms/index.html' }
        ],
        select: function (event, ui) {
            window.location = ui.item.url;
        }
    });
});